'use client'
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../app/styles/globals.css"
import "../app/styles/style.css"
import "../app/styles/custom.css"
import "../app/styles/custom1.css"
import "../app/styles/custom2.css"
import Script from "next/script";
import { Noto_Sans } from 'next/font/google'
import Header from "@/component/partials/Header";
const noto = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
})


 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <style jsx global>{`
        html {
          font-family: ${noto.style.fontFamily};
        }
      `}</style>
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" />
      </head>
      <body >
        <Header/>
        {children}
      </body>
    </html>
  );
}
