'use client'
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../app/styles/globals.css"
import "../app//styles/style.css"
import "../app//styles/custom.css"
import { Noto_Sans } from 'next/font/google'
import Header from "@/component/partials/Header";
const noto = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
})


 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <style jsx global>{`
        html {
          font-family: ${noto.style.fontFamily};
        }
      `}</style>
      <body >
        <Header/>
        {children}
      </body>
    </html>
  );
}
